# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-01 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lr_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greatWords', models.TextField(max_length=500)),
                ('wordsmith', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_poster', to='lr_app.User')),
                ('favorited_by', models.ManyToManyField(related_name='appreciator', to='lr_app.User')),
            ],
        ),
    ]
