# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-01 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
